CREATE TABLE "orders" (
	"id" serial PRIMARY KEY NOT NULL,
	"product_id" integer,
	"product_slug" text NOT NULL,
	"product_title" text DEFAULT '',
	"qty" integer DEFAULT 1 NOT NULL,
	"unit_price" integer DEFAULT 0 NOT NULL,
	"total" integer DEFAULT 0 NOT NULL,
	"full_name" text NOT NULL,
	"phone" text NOT NULL,
	"wilaya_code" text NOT NULL,
	"wilaya_name" text DEFAULT '',
	"commune" text NOT NULL,
	"address" text DEFAULT '',
	"notes" text DEFAULT '',
	"status" text DEFAULT 'new',
	"fb_event_id" text,
	"fbp" text,
	"fbc" text,
	"client_ip" text,
	"user_agent" text,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "products" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"title" text NOT NULL,
	"subtitle" text DEFAULT '',
	"price" integer NOT NULL,
	"old_price" integer,
	"stock" integer DEFAULT 100,
	"images" jsonb DEFAULT '[]'::jsonb,
	"video_url" text DEFAULT '',
	"description" text DEFAULT '',
	"features" jsonb DEFAULT '[]'::jsonb,
	"rating" text DEFAULT '4.8',
	"reviews_count" integer DEFAULT 127,
	"cta_text" text DEFAULT 'اطلب الآن — الدفع عند الاستلام',
	"active" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "products_slug_unique" UNIQUE("slug")
);
